service: python-sls-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
  
  return_words:
    handler: scrabble_handler.return_words
    events:
      - httpApi:
          path: /return_words
          method: post
